from turtle import Turtle, done
julie = Turtle()

julie.penup()
julie.goto(0, -150)
julie.pendown()
julie.pen(pencolor="red", fillcolor="red", pensize=3)
julie.left(45)
julie.begin_fill()
julie.forward(200)
julie.circle(100, 180)
julie.right(90)
julie.circle(100, 180)
julie.forward(200)
julie.end_fill()
julie.penup()
julie.home()
julie.pen(pencolor="#FBAF40")
julie.write("KSI", align="center", font=("Arial", 60, "bold"))
julie.hideturtle()
done()